# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33831320825af261ea61f121293cac5eaca9696d93e99d9446b9dc75b5e0a3644f4f8dd5a4e3eb5c737e66fd66d765b7e8eb94a1c3fa5ef4ec2a88ac422cb976

test:
  secret_key_base: 432ae3d5642e42bc09be45e1aaea6b9b3a1dd819cb9ce132f1dcf3f72887189f84397ae1f6f2b6fcad805714d1ebca00eeff1535ad746863900152e7b1c4dcca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
